---
kind: pipeline
type: exec
name: Build and Deploy AGLDWG Ontologies

platform:
  os: linux
  arch: amd64

steps:
- name: Plot Ontology
  failure: ignore
  commands:
    - ls
    - pwd
    
    # Clone Plot Ontology repository
    - git clone https://@bitbucket.org/terndatateam/ternplotdata-ontology.git

    # Copy RDF to web directory.
    - cd ternplotdata-ontology/schema
    - mkdir -p /var/www/def/plot
    - cp plot.ttl /var/www/def/plot/index.ttl

    # Clone and run pyLODE
    - git clone https://github.com/RDFLib/pyLODE.git
    - mkdir -p pyLODE/src/pylode/output_files
    - cp pylode_inject.yml pyLODE/src/pylode/output_files
    - cd pyLODE
    - apt install python3-pip -y
    - pip3 install -r requirements.txt
    - cd src/pylode/bin
    - pwd
    - ./pylode -i ../../../../plot.ttl --css true
    - cd ../output_files 
    - mv doc.html index.html

    # Clone pyLODE Inject to inject logos and figures
    - git clone https://github.com/edmondchuc/pylode-inject.git
    - pip3 install -r pylode-inject/requirements.txt
    # Click requires UTF-8 encoding on host system
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - ls
    - python3 pylode-inject/pylode_inject.py pylode_inject.yml index.html index.html

    # Copy HTML and CSS to web directory
    - ls
    - cp index.html style.css /var/www/def/plot

- name: Datatype Ontology
  failure: ignore
  commands:
    - ls
    - pwd

    # Datatype Ontology repository already cloned by Plot Ontology step
    # - git clone https://@bitbucket.org/terndatateam/ternplotdata-ontology.git
    - cd ternplotdata-ontology/schema
    - mkdir -p /var/www/def/datatype
    - cp datatype.ttl /var/www/def/datatype/index.ttl

    # Clone and run pyLODE - pyLODE already cloned by Plot Ontology step
    # - git clone https://github.com/RDFLib/pyLODE.git
    - cd pyLODE
    - apt install python3-pip -y
    - pip3 install -r requirements.txt
    - cd src/pylode/bin
    - ./pylode -i ../../../../datatype.ttl --css true
    - cd ../output_files 
    - mv doc.html index.html

    # Copy HTML and CSS to web directory
    - cp index.html style.css /var/www/def/datatype